config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :communication_details
  resources :contacts
  root to: 'visitors#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact, inverse_of: :addresses
  validates :contact, presence: true
  def primary_address
    (self.address_line1 || "") + "-" + (self.country || "")
  end
end

app/models/communication_detail.rb
class CommunicationDetail < ActiveRecord::Base
  belongs_to :contact, inverse_of: :communication_details
  validates :contact, presence: true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :addresses, inverse_of: :contact
  has_many :communication_details, inverse_of: :contact
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :communication_details, reject_if: :all_blank, allow_destroy: true
  
  def name
    self.first_name || "" + self.last_name || ""
  end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:address_line1, :country, :contact_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/communication_details_controller.rb
class CommunicationDetailsController < ApplicationController
  before_action :set_communication_detail, only: [:show, :edit, :update, :destroy]

  # GET /communication_details
  # GET /communication_details.json
  def index
    @communication_details = CommunicationDetail.all
  end

  # GET /communication_details/1
  # GET /communication_details/1.json
  def show
  end

  # GET /communication_details/new
  def new
    @communication_detail = CommunicationDetail.new
  end

  # GET /communication_details/1/edit
  def edit
  end

  # POST /communication_details
  # POST /communication_details.json
  def create
    @communication_detail = CommunicationDetail.new(communication_detail_params)

    respond_to do |format|
      if @communication_detail.save
        format.html { redirect_to @communication_detail, notice: 'Communication detail was successfully created.' }
        format.json { render :show, status: :created, location: @communication_detail }
      else
        format.html { render :new }
        format.json { render json: @communication_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communication_details/1
  # PATCH/PUT /communication_details/1.json
  def update
    respond_to do |format|
      if @communication_detail.update(communication_detail_params)
        format.html { redirect_to @communication_detail, notice: 'Communication detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @communication_detail }
      else
        format.html { render :edit }
        format.json { render json: @communication_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communication_details/1
  # DELETE /communication_details/1.json
  def destroy
    @communication_detail.destroy
    respond_to do |format|
      format.html { redirect_to communication_details_url, notice: 'Communication detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communication_detail
      @communication_detail = CommunicationDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def communication_detail_params
      params.require(:communication_detail).permit(:phone, :contact_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.addresses.build
    @contact.communication_details.build
  end

  # GET /contacts/1/edit
  def edit
    @contact.addresses.build unless @contact.addresses.present?
    @contact.communication_details.build unless @contact.communication_details.present?
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.js
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
        format.js
      else
        format.html { render :edit }
        format.js
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, addresses_attributes: [:id, :address_line1, :country, :_destroy], communication_details_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communication_details_helper.rb
module CommunicationDetailsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address_fields.slim
.nested-fields
  = f.input :address_line1
  = f.input :country, as: :string
  = link_to_remove_association "remove address",  f

app/views/contacts/_communication_detail_fields.slim
.nested-fields
  = f.input :phone
  = link_to_remove_association "remove phone",  f

app/views/contacts/_form.html.slim
= simple_form_for(@contact, remote: true) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    ul.nav.nav-tabs
      li.active
        a data-toggle="tab" href="#address_tab" Address
      li
        a data-toggle="tab" href="#communication_detail"  Communication Detail
    .tab-content
      #address_tab.tab-pane.fade.in.active
        h3 Addresses
        #addresses
          = f.simple_fields_for :addresses do |address|
            = render 'address_fields', f: address
          .links
            = link_to_add_association 'add address', f, :addresses
      #communication_detail.tab-pane.fade
        h3 Communication Details
        #communication_details
          = f.simple_fields_for :communication_details do |communication_detail|
            = render 'communication_detail_fields', f: communication_detail
          .links
            = link_to_add_association 'add phone', f, :communication_details

  .form-actions
    = f.button :submit

app/views/contacts/edit.html.slim
h1 Editing contact

== render 'form'

= link_to 'Show', @contact
'|
= link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1 Listing contacts

table.table.table-striped
  thead
    tr
      th Name
      th Email
      th Primary Address
      th Primary Phone
      th
      th
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = contact.name
        td = contact.email
        td = contact.addresses.first.primary_address if contact.addresses.present?
        td = contact.communication_details.first.phone if contact.communication_details.present?
        td = link_to 'Show', contact
        td = link_to 'Edit', edit_contact_path(contact)
        td = link_to 'Destroy', contact, data: {:confirm => 'Are you sure?'}, :method => :delete
br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.slim
h1 New contact

== render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.slim
p#notice = notice

p
  strong First name:
  = @contact.first_name
p
  strong Last name:
  = @contact.last_name

= link_to 'Edit', edit_contact_path(@contact)
'|
= link_to 'Back', contacts_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Contacts', contacts_path, class: 'navbar-brand'
      = link_to 'New Contact', new_contact_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Contanct Manager'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Contanct Manager'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/visitors/index.html.erb
<h3>Welcome</h3>